const Menu = {
    data() {
        return {
            menus: [],//原始菜单数据
            menuSelected: "",//当前选中的菜单 
            cmdSelected: "",// 当前选中的命令
            filterMenu: [],//选命令后筛选出的菜单{rootIndex:1,action:[tab],cmd:CMD}
            currentMenu: {},//当前菜单{action:tab,children{}}
            commands: [
                "COMMAND_ADD_BOOKMARK",
                "COMMAND_CLIPBOARD_PASTE_AS_PLAIN_TEXT_OR_PASTE_AND_GO",
                "COMMAND_COPY_SELECTION_TO_NOTE",
                "COMMAND_FULLSCREEN",
                "COMMAND_MAIL_ENABLE_SENDER_VIEW",
                "COMMAND_MAIL_ENABLE_THREADED_VIEW",
                "COMMAND_MAIL_FORWARD",
                "COMMAND_MAIL_GOTO_NEXT_UNREAD",
                "COMMAND_MAIL_GOTO_PREVIOUS_UNREAD",
                "COMMAND_MAIL_MARK_READ",
                "COMMAND_MAIL_MARK_READ_AND_GOTO_NEXT_UNREAD",
                "COMMAND_MAIL_MARK_THREAD_READ",
                "COMMAND_MAIL_MARK_THREAD_UNREAD",
                "COMMAND_MAIL_MARK_UNREAD",
                "COMMAND_MAIL_REPLY",
                "COMMAND_MAIL_REPLY_ALL",
                "COMMAND_TAB_VIEW_PAGE_SOURCE",
                "COMMAND_TOGGLE_STARTPAGE_NAVIGATION",
                "CONTEXT_ADD_BOOKMARK_TO_SPEEDDIAL",
                "CONTEXT_ADD_FLAG",
                "CONTEXT_ADD_FOLDER_TO_SPEEDDIAL",
                "CONTEXT_BOOKMARK",
                "CONTEXT_BOOKMARK_ALL",
                "CONTEXT_BOOKMARK_STACK",
                "CONTEXT_CLEAR_THUMBNAIL",
                "CONTEXT_CLONE",
                "CONTEXT_CLOSE",
                "CONTEXT_CLOSE_LEFT",
                "CONTEXT_CLOSE_OTHER",
                "CONTEXT_CLOSE_RIGHT",
                "CONTEXT_CLOSE_TABSTACK",
                "CONTEXT_COLLAPSE_ALL",
                "CONTEXT_COMPOSE_MAIL",
                "CONTEXT_CONTAINER_BACKWARD_HISTORY",
                "CONTEXT_CONTAINER_CLOSED_TAB",
                "CONTEXT_CONTAINER_CUSTOMIZE_TOOLBAR",
                "CONTEXT_CONTAINER_DEFAULT_ACTION",
                "CONTEXT_CONTAINER_FLAGS",
                "CONTEXT_CONTAINER_FORWARD_HISTORY",
                "CONTEXT_CONTAINER_LABELS",
                "CONTEXT_CONTAINER_MOVE",
                "CONTEXT_CONTAINER_MOVE_TO_WINDOW",
                "CONTEXT_CONTAINER_PERIODIC_TIMER",
                "CONTEXT_CONTAINER_PWA",
                "CONTEXT_CONTAINER_REG_PANELS",
                "CONTEXT_CONTAINER_REMOVED_PANELS",
                "CONTEXT_CONTAINER_SEARCH",
                "CONTEXT_CONTAINER_SORT",
                "CONTEXT_CONTAINER_TOOLBAR",
                "CONTEXT_CONTAINER_TRASH",
                "CONTEXT_CONTAINER_WEB_PANELS",
                "CONTEXT_COPY",
                "CONTEXT_COPY_ADDRESS",
                "CONTEXT_COPY_PATH",
                "CONTEXT_CUSTOMIZE",
                "CONTEXT_CUT",
                "CONTEXT_DELETE",
                "CONTEXT_DESKTOP_VERSION",
                "CONTEXT_EDIT",
                "CONTEXT_EMPTY_TRASH",
                "CONTEXT_EXPAND_ALL",
                "CONTEXT_EXPORT",
                "CONTEXT_EXPORT_ALL",
                "CONTEXT_FILEMANAGER",
                "CONTEXT_FILTER_BY",
                "CONTEXT_GOTO",
                "CONTEXT_HIBERNATE_BACKGROUND",
                "CONTEXT_HIBERNATE_SELECTED_BACKGROUND_TABS",
                "CONTEXT_HIBERNATE_TAB",
                "CONTEXT_HIBERNATE_TABSTACK",
                "CONTEXT_IMPORT",
                "CONTEXT_MARK_AS_SPAM",
                "CONTEXT_MENU_OPEN",
                "CONTEXT_MENU_PANEL",
                "CONTEXT_MOBILE_VERSION",
                "CONTEXT_MOVE",
                "CONTEXT_MOVE_LEFT",
                "CONTEXT_MOVE_RIGHT",
                "CONTEXT_MOVE_STACK_LEFT",
                "CONTEXT_MOVE_STACK_RIGHT",
                "CONTEXT_MOVE_TO_BOOKMARK_BAR",
                "CONTEXT_MUTE",
                "CONTEXT_MUTE_OTHER",
                "CONTEXT_NEW",
                "CONTEXT_NEW_BOOKMARK",
                "CONTEXT_NEW_FOLDER",
                "CONTEXT_NEW_FROM_SELECTION",
                "CONTEXT_NEW_ITEM",
                "CONTEXT_NEW_SEPARATOR",
                "CONTEXT_NEW_STACK",
                "CONTEXT_NEW_STACK_FOR_HOST",
                "CONTEXT_NOT_SPAM",
                "CONTEXT_OPEN_ADDRESS",
                "CONTEXT_OPEN_ALL",
                "CONTEXT_OPEN_FILE",
                "CONTEXT_OPEN_IN",
                "CONTEXT_OPEN_IN_NEW_BACKGROUND_TAB",
                "CONTEXT_OPEN_IN_NEW_TAB",
                "CONTEXT_OPEN_IN_NEW_WINDOW",
                "CONTEXT_OPEN_IN_PRIVATE_WINDOW",
                "CONTEXT_OPEN_IN_TAB",
                "CONTEXT_OPTIMIZE_FS_VIDEOS",
                "CONTEXT_PASTE",
                "CONTEXT_PIN",
                "CONTEXT_RELOAD",
                "CONTEXT_REMOVE",
                "CONTEXT_REMOVE_ALL_FINISHED",
                "CONTEXT_REMOVE_FLAG",
                "CONTEXT_REMOVE_WEB_PANEL",
                "CONTEXT_RENAME",
                "CONTEXT_REOPEN",
                "CONTEXT_RESTART",
                "CONTEXT_RESUME",
                "CONTEXT_SAVE",
                "CONTEXT_SAVE_ALL",
                "CONTEXT_SAVE_SESSION",
                "CONTEXT_SEND",
                "CONTEXT_SENDER",
                "CONTEXT_SENDER_IS_MAILING_LIST",
                "CONTEXT_SEPARATE_WIDTH",
                "CONTEXT_SET_BOOKMARK_BAR",
                "CONTEXT_SET_SPEEDDIAL",
                "CONTEXT_SET_THUMBNAIL",
                "CONTEXT_SETTINGS",
                "CONTEXT_STOP",
                "CONTEXT_TABSTACK_BY_HOST",
                "CONTEXT_TABSTACK_BY_HOSTS",
                "CONTEXT_TABSTACK_BY_SELECTION",
                "CONTEXT_TABSTACK_MOVE",
                "CONTEXT_TABSTACK_REMOVE_FROM",
                "CONTEXT_TABSTACK_RENAME",
                "CONTEXT_TABSTACK_UNGROUP",
                "CONTEXT_THREAD",
                "CONTEXT_TILE_TABS",
                "CONTEXT_TILE_TABSTACK",
                "CONTEXT_TOGGLE_SUBSTRIP_LOCK",
                "CONTEXT_UNMUTE",
                "CONTEXT_UNPIN",
                "CONTEXT_UNSET_BOOKMARK_BAR",
                "CONTEXT_UNSET_SPEEDDIAL",
                "CONTEXT_UNTILE_SELECTION",
                "CONTEXT_UNTILE_TABS",
                "CONTEXT_UNTILE_TABSTACK",
                "CONTEXT_VIEW_ALL_MESSAGES",
                "DOCUMENT_ADD_AS_SEARCH_ENGINE",
                "DOCUMENT_ADD_LINK_TO_BOOKMARKS",
                "DOCUMENT_ADD_LINK_TO_WEBPANEL",
                "DOCUMENT_ADD_TO_CALENDAR",
                "DOCUMENT_ADD_TO_WEBPANEL",
                "DOCUMENT_BACK",
                "DOCUMENT_CAST",
                "DOCUMENT_CONTAINER_AV",
                "DOCUMENT_CONTAINER_DEVELOPER_TOOLS",
                "DOCUMENT_CONTAINER_EXTENSIONS",
                "DOCUMENT_CONTAINER_LINK_SELECTION",
                "DOCUMENT_CONTAINER_LINKED_IMAGE",
                "DOCUMENT_CONTAINER_NOTES",
                "DOCUMENT_CONTAINER_OPEN_IMAGE_IN_PROFILE",
                "DOCUMENT_CONTAINER_OPEN_IN_PROFILE",
                "DOCUMENT_CONTAINER_OPEN_IN_PWA",
                "DOCUMENT_CONTAINER_PLUGIN_ROTATION",
                "DOCUMENT_CONTAINER_SEARCH_WITH",
                "DOCUMENT_CONTAINER_SEND_TO_DEVICES",
                "DOCUMENT_CONTAINER_SPEECH",
                "DOCUMENT_CONTAINER_SPELLCHECK",
                "DOCUMENT_CONTAINER_SPELLCHECK_OPTIONS",
                "DOCUMENT_CONTAINER_WRITING_DIRECTION",
                "DOCUMENT_COPY",
                "DOCUMENT_COPY_ADDRESS",
                "DOCUMENT_COPY_IMAGE",
                "DOCUMENT_COPY_IMAGE_ADDRESS",
                "DOCUMENT_COPY_LINK_ADDRESS",
                "DOCUMENT_COPY_LINK_TEXT",
                "DOCUMENT_CUSTOMIZE",
                "DOCUMENT_CUT",
                "DOCUMENT_EMOJI",
                "DOCUMENT_FORWARD",
                "DOCUMENT_GOTO_URL",
                "DOCUMENT_INSPECT",
                "DOCUMENT_LOOK_UP",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_BACKGROUND_TAB",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_TAB",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_WINDOW",
                "DOCUMENT_OPEN_IMAGE_IN_PRIVATE_WINDOW",
                "DOCUMENT_OPEN_IMAGE_IN_TAB",
                "DOCUMENT_OPEN_IN_NEW_BACKGROUND_TAB",
                "DOCUMENT_OPEN_IN_NEW_TAB",
                "DOCUMENT_OPEN_IN_NEW_WINDOW",
                "DOCUMENT_OPEN_IN_PRIVATE_WINDOW",
                "DOCUMENT_OPEN_IN_TAB",
                "DOCUMENT_PASTE",
                "DOCUMENT_PASTE_AS_PLAIN_TEXT",
                "DOCUMENT_PRINT",
                "DOCUMENT_QR_CODE",
                "DOCUMENT_REDO",
                "DOCUMENT_RELOAD",
                "DOCUMENT_RELOAD_IMAGE",
                "DOCUMENT_SAVE",
                "DOCUMENT_SAVE_IMAGE",
                "DOCUMENT_SAVE_LINK",
                "DOCUMENT_SEARCH",
                "DOCUMENT_SEARCH_FOR IMAGE",
                "DOCUMENT_SELECT_ALL",
                "DOCUMENT_SEND_BY_MAIL",
                "DOCUMENT_SEND_LINK_BY_MAIL",
                "DOCUMENT_SHOW_FULL_ADDRESS",
                "DOCUMENT_SHOW_IMAGE_PROPERTIES",
                "DOCUMENT_SHOW_PASSWORDS",
                "DOCUMENT_SUGGEST_PASSWORD",
                "DOCUMENT_UNDO",
                "DOCUMENT_USE_IMAGE_AS_STARTPAGE_BACKGROUND",
                "MENU_PANEL",

            ]
        };
    },
    computed: {
        menuShow: function () {
            return Object.keys(this.currentMenu).length ? true : false;
        },
        filterMenuShow: function () {
            return this.filterMenu.length ? true : false;
        }
    },
    methods: {
        importFile() {
            document.querySelector("#import").click();
        },
        loadJson(e) {
            let file = e.target.files[0];
            if (file) this.readJson(file);
        },
        readJson(file) {
            this.menuSelected = "";
            this.cmdSelected = "";
            let reader = new FileReader();
            reader.onload = (e) => {
                this.menus = JSON.parse(e.target.result);

            };
            reader.readAsText(file);
        },
        showMenu() {
            this.cmdSelected = "";
            this.filterMenu = [];
            let cmd = this.menuSelected;
            this.currentMenu = { action: cmd, cmd: cmd, menu: this.menus[cmd].children };
        },
        searchMenu() {
            console.log(this.cmdSelected)
            this.menuSelected = "";
            this.filterMenu = [];
            this.currentMenu = {};
            this.menus.forEach((menu, index) => {
                if ("children" in menu) {//有children的才是菜单
                    menu.children.forEach((m, i) => {//第一层
                        if (m.action == this.cmdSelected) {//找到命令，添加菜单索引
                            this.filterMenu.push({ rootIndex: index, action: [this.menus[index].action], cmd: this.cmdSelected });
                        } else if ("children" in m) {
                            m.children.forEach(n => {//第二层
                                if (n.action == this.cmdSelected) {
                                    this.filterMenu.push({ rootIndex: index, action: [this.menus[index].action, m.action], cmd: this.cmdSelected });
                                }
                            });
                        }
                    });
                }
            });
        },
        gMenu(item) {
            this.currentMenu = { action: item.action, menu: this.menus[item.rootIndex].children, cmd: item.cmd };
        }
    },

    created() {
        fetch("./contextmenu.json").then(res => {
            return res.json();
        }).then(json => this.menus = json);

    }
};
const app = Vue.createApp(Menu);
app.component(
    'menu-item', {
    props: ['item', 'action', 'cmd'],
    template:
        `<template v-if="Array.isArray(action)">
       <template v-if="item.action == action[1]" >
         <div class="item selected" :class="item.type"><menu-span :item="item"></menu-span></div>
         <div class="menu submenu">
           <menu-item v-for="item in item.children" :item="item" :action="action[1]" :cmd="cmd"></menu-item>
         </div>
       </template>
       <div v-else-if="item.action == cmd" class="item selected" :class="item.type"><menu-span :item="item"></menu-span></div>
       <div v-else class="item" :class="item.type"><menu-span :item="item"></menu-span></div>
     </template>
     <div v-else-if="item.action == cmd" class="item selected" :class="item.type"><menu-span :item="item"></menu-span></div>
     <div v-else class="item" :class="item.type"><menu-span :item="item"></menu-span></div>`
},

)
app.component(
    'menu-span', {
    props: ['item'],
    template: `<span v-if="item.type=='container'">[{{ $t(item.action) }}]</span><span v-else>{{$t(item.action)}}</span>`
})

const messages = {
    'en': {
        select_a_menu: 'Select a Menu',
        select_a_cmd: 'Select a Command',
        import: 'Import',
        vivaldi: "Vivaldi Button Menu",
        menubar: "Horizontal Menu",
        audiovideo: "Audio and Video",
        image: "Image",
        link: "Link",
        page: "Page",
        selection: "Selection",
        docedit: "Text Field",
        contactlist: "Contacts",
        mailsearchlist: "Message List",
        speeddialitem: "Speed Dial Button",
        startpage: "Start Page",
        startpagebar: "Start Page Bar",
        panelbar: "Panel Bar",
        panelbaritem: "Panel Bar Button",
        tab: "Tab",
        tabbar: "Tab Bar",
        tabstackthumbnails: "Tab Stack Thumbnails",
        closedtab: "Tab Trash Can",
        windowlist: "Window List",
        bookmarkbar: "Bookmark Bar",
        bookmarkbaritem: "Bookmark Bar Button",
        bookmarklist: "Bookmark List",
        backwardbutton: "Back Button",
        forwardbutton: "Forward Button",
        rewindbutton: "Rewind Button",
        fastforwardbutton: "Fast Forward Button",
        reloadbutton: "Reload Button",
        homebutton: "Home Button",
        urledit: "Text Field",
        downloadlist: "Download List",
        historylist: "History List",
        noteslist: "Notes List",
        uiedit: "Text Field",
        panelbarregitem: "panelbarregitem",
        COMMAND_OPEN_LINK: "Open Link",
        CONTEXT_BOOKMARK: "Add Active Tab",
        CONTEXT_CONTAINER_PWA: "All Progressive Web Apps",
        CONTEXT_CONTAINER_MOVE_TO_WINDOW: "All Window Destinations",
        CONTEXT_BOOKMARK_ALL: "Bookmark All Tabs",
        CONTEXT_BOOKMARK_STACK: "Bookmark Tab Stack",
        CONTEXT_BOOKMARK: "Bookmark Tab",
        CONTEXT_CLONE: "Clone Tab",
        CONTEXT_CLOSE_OTHER: "Close Other Tabs",
        CONTEXT_CLOSE_TABSTACK: "Close Tab Stack",
        CONTEXT_CLOSE: "Close Tab",
        CONTEXT_CLOSE_LEFT: "Close Tabs to the Left",
        CONTEXT_CLOSE_RIGHT: "Close Tabs to the Right",
        CONTEXT_COPY: "Copy",
        CONTEXT_CUSTOMIZE: "Customize",
        CONTEXT_CUT: "Cut",
        CONTEXT_DELETE: "Delete",
        CONTEXT_EDIT: "Edit",
        CONTEXT_HIBERNATE_BACKGROUND: "Hibernate Background Tabs",
        CONTEXT_HIBERNATE_SELECTED_BACKGROUND_TABS: "Hibernate Selected Background Tabs",
        CONTEXT_HIBERNATE_TABSTACK: "Hibernate Tab Stack",
        CONTEXT_HIBERNATE_TAB: "Hibernate Tab",
        CONTEXT_MOVE_LEFT: "Left",
        CONTEXT_MOVE_STACK_LEFT: "Left",
        CONTEXT_TOGGLE_SUBSTRIP_LOCK: "Lock Second Tab Row",
        CONTEXT_TABSTACK_MOVE: "Move Tab Stack",
        CONTEXT_MOVE: "Move Tab",
        CONTEXT_MUTE_OTHER: "Mute Other Tabs",
        CONTEXT_MUTE: "Mute Tab",
        CONTEXT_NEW_BOOKMARK: "New Bookmark",
        CONTEXT_NEW_FOLDER: "New Folder",
        CONTEXT_NEW_SEPARATOR: "New Separator",
        CONTEXT_NEW: "New Tab",
        CONTEXT_OPEN_IN_NEW_BACKGROUND_TAB: "Open in Background Tab",
        CONTEXT_OPEN_IN_NEW_TAB: "Open in New Tab",
        CONTEXT_OPEN_IN_NEW_WINDOW: "Open in New Window",
        CONTEXT_OPEN_IN_PRIVATE_WINDOW: "Open in Private Window",
        CONTEXT_OPEN_IN_TAB: "Open",
        CONTEXT_OPTIMIZE_FS_VIDEOS: "Optimize videos",
        CONTEXT_PASTE: "Paste",
        CONTEXT_CONTAINER_PERIODIC_TIMER: "Periodic Reload",
        CONTEXT_PIN: "Pin Tab",
        CONTEXT_RELOAD: "Reload Tab",
        CONTEXT_TABSTACK_REMOVE_FROM: "Remove from Tab tack",
        CONTEXT_TABSTACK_RENAME: "Rename Tab tack",
        CONTEXT_REOPEN: "Reopen Closed ab",
        CONTEXT_MOVE_RIGHT: "Right",
        CONTEXT_MOVE_STACK_RIGHT: "Right",
        CONTEXT_SAVE_SESSION: "Save All Tabs as ession",
        CONTEXT_CONTAINER_SORT: "Sort Options",
        CONTEXT_TABSTACK_BY_SELECTION: "Stack Selected abs",
        CONTEXT_TABSTACK_BY_HOST: "Stack Tabs by ost",
        CONTEXT_TABSTACK_BY_HOSTS: "Stack Tabs by osts",
        CONTEXT_TILE_TABSTACK: "Tile Tab tack",
        CONTEXT_TILE_TABS: "Tile tabs",
        CONTEXT_UNPIN: "Unpin tab",
        CONTEXT_TABSTACK_UNGROUP: "Unstack Tabs",
        CONTEXT_UNTILE_SELECTION: "Untile Selection",
        CONTEXT_UNTILE_TABSTACK: "Untile Tab Stack",
        CONTEXT_RENAME: "Rename",
        CONTEXT_CONTAINER_CLOSED_TAB: "All Closed Tabs",
        CONTEXT_CONTAINER_REG_PANELS: "Regular Panels",
        CONTEXT_CONTAINER_WEB_PANELS: "Web Panels",
        CONTEXT_CONTAINER_REMOVED_PANELS: "Removed Panels",
        CONTEXT_MENU_OPEN: "Open in",
        CONTEXT_COPY_ADDRESS: "Copy Panel Address",
        CONTEXT_DESKTOP_VERSION: "Show Desktop Version",
        CONTEXT_MOBILE_VERSION: "Show Mobile Version",
        CONTEXT_SEPARATE_WIDTH: "Separate Width",
        CONTEXT_CONTAINER_TOOLBAR: "Toolbar",
        CONTEXT_REMOVE_WEB_PANEL: "Remove Web Panel",
        CONTEXT_MENU_PANEL: "Panels",
        CONTEXT_CONTAINER_BACKWARD_HISTORY: "Backward History",
        CONTEXT_CONTAINER_CUSTOMIZE_TOOLBAR: "Customize",
        CONTEXT_CONTAINER_FORWARD_HISTORY: "Forward History",
        CONTEXT_OPEN_ALL: "Open All Bookmarks",
        CONTEXT_SET_THUMBNAIL: "Select Custom Thumbnail...",
        CONTEXT_CLEAR_THUMBNAIL: "Clear Custom Thumbnail",
        COMMAND_TOGGLE_STARTPAGE_NAVIGATION: "Show Start Page Navigation",
        CONTEXT_ADD_BOOKMARK_TO_SPEEDDIAL: "Add Bookmark to Speed Dial",
        CONTEXT_ADD_FOLDER_TO_SPEEDDIAL: "Add Speed Dial Folder",
        CONTEXT_REMOVE: "Remove",
        CONTEXT_SEND: "Send",
        COMMAND_MAIL_REPLY: "Reply to Message",
        COMMAND_MAIL_REPLY_ALL: "Reply All",
        COMMAND_MAIL_MARK_READ: "Mark Message as Read",
        COMMAND_MAIL_MARK_UNREAD: "Mark Message as Unread",
        CONTEXT_GOTO: "Go to",
        CONTEXT_CONTAINER_MOVE: "Move",
        CONTEXT_ADD_FLAG: "Add Flag",
        CONTEXT_REMOVE_FLAG: "Move Flag",
        CONTEXT_CONTAINER_FLAGS: "All Flags",
        CONTEXT_CONTAINER_LABELS: "All Labels",
        CONTEXT_MARK_AS_SPAM: "Mark Message as Spam",
        COMMAND_MAIL_GOTO_NEXT_UNREAD: "Next Unread",
        COMMAND_MAIL_GOTO_PREVIOUS_UNREAD: "Previous Unread",
        COMMAND_MAIL_MARK_READ_AND_GOTO_NEXT_UNREAD: "Mark Message as Read and Go to Next Unread",
        CONTEXT_NOT_SPAM: "Not Spam",
        CONTEXT_CONTAINER_TRASH: "Trash elements",
        CONTEXT_SENDER: "Sender",
        COMMAND_MAIL_ENABLE_SENDER_VIEW: "Show Messages from Sender",
        CONTEXT_SENDER_IS_MAILING_LIST: "Treat Sender as a Mailing List",
        COMMAND_MAIL_ENABLE_THREADED_VIEW: "Show Message Thread",
        COMMAND_MAIL_MARK_THREAD_READ: "Mark Message Thread as Read",
        COMMAND_MAIL_MARK_THREAD_UNREAD: "Mark Message Thread as Unread",
        CONTEXT_THREAD: "Thread",
        CONTEXT_EXPAND_ALL: "Expand All Threads",
        CONTEXT_COLLAPSE_ALL: "Collapse All Threads",
        CONTEXT_SET_SPEEDDIAL: "Use as Speed Dial",
        CONTEXT_UNSET_SPEEDDIAL: "Remove from Speed Dial",
        CONTEXT_SET_BOOKMARK_BAR: "Set as Bookmark Bar Folder",
        CONTEXT_UNSET_BOOKMARK_BAR: "Remove as Bookmark Bar Folder",
        CONTEXT_MOVE_TO_BOOKMARK_BAR: "Move to Bookmark Bar Folder",
        CONTEXT_NEW_ITEM: "New Bookmark",
        CONTEXT_EMPTY_TRASH: "Empty Trash",
        CONTEXT_SETTINGS: "Settings",
        CONTEXT_OPEN_ADDRESS: "Open Note Address",
        CONTEXT_NEW_FROM_SELECTION: "Copy Selection to New Note",
        CONTEXT_FILTER_BY: "Filter by Address",
        CONTEXT_SAVE: "Save as Bookmarks",
        CONTEXT_OPEN_FILE: "Open",
        CONTEXT_OPEN_IN: "Open Image in",
        CONTEXT_FILEMANAGER: "Show in File Manager",
        CONTEXT_COPY_PATH: "Copy Local Path",
        CONTEXT_RESTART: "Restart",
        CONTEXT_STOP: "Stop",
        CONTEXT_RESUME: "Resume Download",
        CONTEXT_REMOVE_ALL_FINISHED: "Remove All Finished",
        CONTEXT_NEW_STACK: "Stack Selected Tabs",
        CONTEXT_NEW_STACK_FOR_HOST: "Stack Tabs by Host",
        CONTEXT_UNTILE_TABS: "Untile Tabs",
        CONTEXT_UNMUTE: "Unmute Tab",
        CONTEXT_SAVE_ALL: "Save All as Bookmarks",
        CONTEXT_IMPORT: "Import Bookmarks...",
        CONTEXT_CONTAINER_SEARCH: "Search",
        CONTEXT_EXPORT: "Save as Session",
        CONTEXT_EXPORT_ALL: "Save All as Session",
        CONTEXT_COMPOSE_MAIL: "Compose Mail",
        CONTEXT_VIEW_ALL_MESSAGES: "View All Messages",
        CONTEXT_CONTAINER_DEFAULT_ACTION: "Default Action",
        DOCUMENT_OPEN_IN_NEW_TAB: "Open Link in New Tab",
        DOCUMENT_OPEN_IN_NEW_BACKGROUND_TAB: "Open Link in Background Tab",
        DOCUMENT_OPEN_IN_TAB: "Open Link",
        DOCUMENT_OPEN_IN_NEW_WINDOW: "Open Link in New Window",
        DOCUMENT_OPEN_IN_PRIVATE_WINDOW: "Open Link in Private Window",
        DOCUMENT_CONTAINER_OPEN_IN_PWA: "Open Link in Progressive Web Apps",
        DOCUMENT_CONTAINER_OPEN_IN_PROFILE: "Open Link in Another Profile",
        DOCUMENT_CONTAINER_SEND_TO_DEVICES: "Send Link to Your Devices",
        DOCUMENT_ADD_LINK_TO_BOOKMARKS: "Bookmark Link",
        DOCUMENT_ADD_LINK_TO_WEBPANEL: "Add Link to Web Panel",
        DOCUMENT_SEND_LINK_BY_MAIL: "Send Link by Mail",
        DOCUMENT_SAVE_LINK: "Save Link As...",
        DOCUMENT_COPY_LINK_ADDRESS: "Copy Link Address",
        DOCUMENT_COPY_LINK_TEXT: "Copy Link Text",
        DOCUMENT_CONTAINER_AV: "Media Controls",
        DOCUMENT_CONTAINER_LINK_SELECTION: "Selection Menu",
        DOCUMENT_CONTAINER_LINKED_IMAGE: "Image Menu",
        DOCUMENT_CONTAINER_EXTENSIONS: "Extensions",
        DOCUMENT_CONTAINER_DEVELOPER_TOOLS: "Developer Tools",
        DOCUMENT_BACK: "Back",
        DOCUMENT_FORWARD: "Forward",
        DOCUMENT_RELOAD: "Reload",
        DOCUMENT_ADD_TO_WEBPANEL: "Add Page to Web Panel",
        DOCUMENT_SEND_BY_MAIL: "Send by Mail",
        DOCUMENT_SAVE: "Save as...",
        DOCUMENT_PRINT: "Print...",
        DOCUMENT_CAST: "Cast...",
        DOCUMENT_COPY_ADDRESS: "Copy Page Address",
        DOCUMENT_QR_CODE: "Create QR Code for This Page",
        DOCUMENT_CONTAINER_PLUGIN_ROTATION: "Plugin Rotation Commands",
        DOCUMENT_OPEN_IMAGE_IN_NEW_TAB: "Open Image in New Tab",
        DOCUMENT_OPEN_IMAGE_IN_NEW_BACKGROUND_TAB: "Open Image in Background Tab",
        DOCUMENT_OPEN_IMAGE_IN_TAB: "Open Image",
        DOCUMENT_OPEN_IMAGE_IN_NEW_WINDOW: "Open Image in New Window",
        DOCUMENT_OPEN_IMAGE_IN_PRIVATE_WINDOW: "Open Image in Private Window",
        DOCUMENT_CONTAINER_OPEN_IMAGE_IN_PROFILE: "Open Image in Another Profile",
        DOCUMENT_SAVE_IMAGE: "Save Image As...",
        DOCUMENT_COPY_IMAGE_ADDRESS: "Copy Image Address",
        DOCUMENT_COPY_IMAGE: "Copy Image",
        DOCUMENT_SHOW_IMAGE_PROPERTIES: "Image Properties...",
        DOCUMENT_USE_IMAGE_AS_STARTPAGE_BACKGROUND: "Use Image as Start Page Background",
        DOCUMENT_RELOAD_IMAGE: "Reload Image",
        "DOCUMENT_SEARCH_FOR IMAGE": "Search for Image",
        DOCUMENT_SUGGEST_PASSWORD: "Suggest Password...",
        DOCUMENT_SHOW_PASSWORDS: "Show all Saved Passwords...",
        DOCUMENT_CONTAINER_SPELLCHECK: "Spell Check",
        DOCUMENT_LOOK_UP: "Look Up “”",
        DOCUMENT_EMOJI: "Emoji && Symbols",
        DOCUMENT_UNDO: "Undo",
        DOCUMENT_REDO: "Redo",
        DOCUMENT_CUT: "Cut",
        DOCUMENT_COPY: "Copy",
        DOCUMENT_PASTE: "Paste",
        DOCUMENT_PASTE_AS_PLAIN_TEXT: "Paste as Plain Text",
        DOCUMENT_SELECT_ALL: "Select All",
        DOCUMENT_GOTO_URL: "Go to “”",
        DOCUMENT_ADD_AS_SEARCH_ENGINE: "Add as Search Engine...",
        DOCUMENT_CONTAINER_NOTES: "Insert Notes",
        DOCUMENT_CONTAINER_SPELLCHECK_OPTIONS: "Spell Check Options",
        DOCUMENT_CONTAINER_WRITING_DIRECTION: "Writing Direction",
        DOCUMENT_SEARCH: "Search xx for “”",
        DOCUMENT_CONTAINER_SEARCH_WITH: "Search With",
        DOCUMENT_CONTAINER_SPEECH: "Speech",
        COMMAND_CLIPBOARD_PASTE_AS_PLAIN_TEXT_OR_PASTE_AND_GO: "Paste and Go",
        DOCUMENT_CUSTOMIZE: "Customize...",
        DOCUMENT_SHOW_FULL_ADDRESS: "Show Full Address",
        DOCUMENT_ADD_TO_CALENDAR: "Add as Calendar Event",
        DOCUMENT_INSPECT: "Inspect",
        COMMAND_OPEN_LINK: "Open Link",
        CONTAINER_CLOSED_TAB: "All Closed Tabs",
        CONTAINER_PINNED_TAB: "All Pinned Tabs",
        CONTAINER_TAB: "All Tabs",
        CONTAINER_WEBPANEL: "All Web Panels",
        CONTAINER_PERIODIC_RELOAD: "Periodic Reload",
        COMMAND_SHOW_ABOUT: "About",
        COMMAND_SHOW_ACCOUNT_SHEET: "Account Sheet",
        COMMAND_ADD_NEW_CALENDAR_ACCOUNT: "Add New Calendar Account",
        COMMAND_MAIL_ADD_NEW_MAIL_ACCOUNT: "Add New Mail Account",
        COMMAND_MAIN_TOGGLE_ADDRESS_BAR: "Address Bar",
        COMMAND_CAPTURE_AREA_TO_CLIPBOARD: "Area to Clipboard",
        COMMAND_CAPTURE_AREA_TO_DISK: "Area to File",
        COMMAND_BLOCK_TRACKING_AND_ADS: "Block / Unblock Ads and Tracking",
        COMMAND_BLOCK_TRACKING: "Block / Unblock Tracking",
        COMMAND_BOOKMARK_SELECTED_TABS: "Bookmark Selected Tabs",
        COMMAND_SHOW_BOOKMARKS: "Bookmarks",
        COMMAND_SHOW_BOOKMARK_PANEL: "Bookmarks Panel",
        COMMAND_BREAKMODE_TOGGLE: "Break Mode",
        COMMAND_SHOW_CALENDAR: "Calendar",
        COMMAND_SHOW_CALENDAR_PANEL: "Calendar Panel",
        COMMAND_START_CHROMECAST: "Cast",
        COMMAND_CHECK_FOR_UPDATES: "Check for Updates",
        COMMAND_CLONE_TAB: "Clone Selected Tabs",
        COMMAND_CLOSE_ALL_BUT_ACTIVE_TAB: "Close Other Tabs",
        COMMAND_CLOSE_TAB: "Close Tab",
        COMMAND_CLOSE_TAB_TO_LEFT: "Close Tabs to the Left",
        COMMAND_CLOSE_TAB_TO_RIGHT: "Close Tabs to the Right",
        COMMAND_CLOSE_WINDOW: "Close Window",
        COMMAND_SHOW_COMMUNITY: "Community Blogs",
        COMMAND_MAIL_COMPOSE_NEW_MESSAGE: "Compose New MessageN",
        COMMAND_SHOW_CONTACTS_PANEL: "Contacts Panel",
        COMMAND_CLIPBOARD_COPY: "Copy",
        COMMAND_COPY_SELECTION_TO_NOTE: "Copy Selected Text to Note",
        COMMAND_ADD_BOOKMARK: "Create Bookmark",
        COMMAND_CLIPBOARD_CUT: "Cut",
        COMMAND_MAIL_DELETE_ALL_PERMANENTLY: "Delete All Permanently",
        COMMAND_SHOW_CLEAR_PRIVATE_DATA: "Delete Browsing Data",
        COMMAND_MAIL_DELETE_PERMANENTLY: "Delete Permanently",
        COMMAND_PAGE_SELECTION_CLEAR: "Deselect Tabs",
        COMMAND_DEVELOPER_TOOLS: "Developer Tools",
        COMMAND_DEVTOOLS_CONSOLE: "Developer Tools Console",
        COMMAND_PAGE_DISABLE_KEYBOARD_SHORTCUTS: "Disable Keyboard Shortcuts",
        COMMAND_TAB_DISABLE_ALL_RELOADS: "Disable Periodic Timers",
        COMMAND_SHOW_DOWNLOADS_PANEL: "Downloads Panel",
        COMMAND_EXIT: "Exit",
        COMMAND_EXPORT_DATA: "Export Bookmarks",
        COMMAND_EXPORT_NOTES: "Export Notes",
        COMMAND_SHOW_EXTENSIONS: "Extensions",
        COMMAND_PAGE_FAST_FORWARD: "Fast Forward",
        COMMAND_FIND_NEXT_IN_PAGE: "Find Next in Page",
        COMMAND_FIND_PREVIOUS_IN_PAGE: "Find Previous in Page",
        COMMAND_FIND_IN_PAGE: "Find in Page",
        COMMAND_FOCUS_BOOKMARKBAR: "Focus Bookmarks Bar",
        COMMAND_FOCUS_MAINMENU: "Focus Main Menu",
        COMMAND_FOCUS_NEXT: "Focus Next Pane",
        COMMAND_FOCUS_WEBVIEW: "Focus Page",
        COMMAND_FOCUS_PANEL: "Focus Panel",
        COMMAND_FOCUS_PANELBAR: "Focus Panel Bar",
        COMMAND_FOCUS_PREVIOUS: "Focus Previous Pane",
        COMMAND_FOCUS_SEARCHFIELD: "Focus Search Field",
        COMMAND_FOCUS_TABBAR: "Focus Tab Bar",
        COMMAND_PAGE_RELOAD_NOCACHE: "Force Page Reload",
        COMMAND_MAIL_FORWARD: "Forward Message",
        COMMAND_FULLSCREEN: "Fullscreen",
        COMMAND_HIBERNATE_OTHER_TABS: "Hibernate Background Tabs",
        COMMAND_HIDE_OTHERS: "Hide Others",
        COMMAND_MAIN_TOGGLE_UI: "Hide UI",
        COMMAND_HIDE_VIVALDI: "Hide Vivaldi",
        COMMAND_SHOW_HISTORY: "History",
        COMMAND_PAGE_BACK: "History Back",
        COMMAND_PAGE_FORWARD: "History Forward",
        COMMAND_SHOW_HISTORY_PANEL: "History Panel",
        COMMAND_PAGE_REWIND: "History Rewind",
        COMMAND_SHOW_HOMEPAGE: "Home",
        COMMAND_TOGGLE_MENU_POSITION: "Horizontal Main Menu",
        COMMAND_TAB_VIEW_PAGE_SOURCE: "View Page Source",
        COMMAND_IMPORT_CALENDAR: "Import Calendar",
        COMMAND_IMPORT_NOTES: "Import Notes",
        COMMAND_IMPORT_DATA: "Import from Applications or Files",
        MENU_PANEL: "MENU_PANEL"
    },
    'zh': {
        select_a_menu: '选择一个菜单',
        select_a_cmd: '选择一个命令',
        import: '导入',
        vivaldi: "Vivaldi 按钮菜单",
        menubar: "水平式",
        image: "图片",
        docedit: "网页文本域",
        selection: "选择",
        link: "链接",
        audiovideo: "音视频",
        page: "页面",
        mailsearchlist: "消息列表",
        contactlist: "联系人",
        startpage: "开始页",
        speeddialitem: "快速拨号按钮",
        startpagebar: "起始页栏",
        panelbar: "面板栏",
        panelbaritem: "面板栏按钮",
        tab: "标签",
        closedtab: "标签回收站",
        tabbar: "标签栏",
        tabstackthumbnails: "标签组缩略图",
        windowlist: "窗口列表",
        bookmarklist: "书签列表",
        bookmarkbar: "书签栏",
        bookmarkbaritem: "书签栏按钮",
        backwardbutton: "后退按钮",
        forwardbutton: "前进按钮",
        rewindbutton: "快退按钮",
        fastforwardbutton: "快进按钮",
        reloadbutton: "重载按钮",
        homebutton: "主页按钮",
        urledit: "地址栏文本域",
        downloadlist: "下载列表",
        historylist: "历史列表",
        uiedit: "文本域",
        noteslist: "笔记列表",
        CONTEXT_NEW: "新建标签",
        CONTEXT_RELOAD: "刷新标签",
        CONTEXT_CLONE: "复制标签",
        CONTEXT_PIN: "锁定标签",
        CONTEXT_UNPIN: "取消锁定",
        CONTEXT_MOVE: "移动标签",
        CONTEXT_MOVE_LEFT: "左侧",
        CONTEXT_MOVE_RIGHT: "右侧",
        CONTEXT_CONTAINER_MOVE_TO_WINDOW: "至窗口",
        CONTEXT_CONTAINER_PERIODIC_TIMER: "定时刷新",
        CONTEXT_MUTE: "静音标签",
        CONTEXT_MUTE_OTHER: "静音其他标签",
        CONTEXT_OPTIMIZE_FS_VIDEOS: "优化全屏视频",
        CONTEXT_BOOKMARK: "加入书签",
        CONTEXT_BOOKMARK_STACK: "标签组加入书签",
        CONTEXT_BOOKMARK_ALL: "全部加入书签",
        CONTEXT_SAVE_SESSION: "保存全部标签为会话",
        CONTEXT_TABSTACK_BY_SELECTION: "所选标签建组",
        CONTEXT_TABSTACK_BY_HOST: "按域名创建标签栈",
        CONTEXT_TABSTACK_BY_HOSTS: "按域名创建标签栈",
        CONTEXT_TABSTACK_RENAME: "重命名标签组",
        CONTEXT_TABSTACK_MOVE: "移动标签组",
        CONTEXT_TABSTACK_REMOVE_FROM: "从标签组移除",
        CONTEXT_TABSTACK_UNGROUP: "解散标签组",
        CONTEXT_TILE_TABSTACK: "平铺标签组",
        CONTEXT_UNTILE_TABSTACK: "取消平铺标签组",
        CONTEXT_TILE_TABS: "平铺标签",
        CONTEXT_UNTILE_SELECTION: "取消平铺所选标签",
        CONTEXT_HIBERNATE_TAB: "休眠标签",
        CONTEXT_HIBERNATE_SELECTED_BACKGROUND_TABS: "休眠所选后台标签",
        CONTEXT_HIBERNATE_TABSTACK: "休眠标签组",
        CONTEXT_HIBERNATE_BACKGROUND: "休眠后台标签",
        CONTEXT_CLOSE: "关闭标签",
        CONTEXT_CLOSE_TABSTACK: "关闭标签组",
        CONTEXT_CLOSE_OTHER: "关闭其他标签",
        CONTEXT_CLOSE_LEFT: "关闭左侧标签",
        CONTEXT_CLOSE_RIGHT: "关闭右侧标签",
        CONTEXT_REOPEN: "重新打开关闭的标签",
        CONTEXT_CONTAINER_PWA: "所有增强型网页应用 PWA",
        CONTEXT_CUSTOMIZE: "自定义",
        CONTEXT_TOGGLE_SUBSTRIP_LOCK: "锁定第二行标签",
        CONTEXT_NEW_BOOKMARK: "新建书签",
        CONTEXT_NEW_FOLDER: "新建文件夹",
        CONTEXT_NEW_SEPARATOR: "新增分割线",
        CONTEXT_CONTAINER_SORT: "排序选项",
        CONTEXT_EDIT: "编辑",
        CONTEXT_RENAME: "重命名",
        CONTEXT_CUT: "剪切",
        CONTEXT_COPY: "复制",
        CONTEXT_PASTE: "粘贴",
        CONTEXT_DELETE: "删除",
        CONTEXT_OPEN_IN_NEW_TAB: "在新标签页打开",
        CONTEXT_OPEN_IN_NEW_BACKGROUND_TAB: "在后台标签页打开",
        CONTEXT_OPEN_IN_TAB: "打开",
        CONTEXT_OPEN_IN_NEW_WINDOW: "在新窗口中打开",
        CONTEXT_OPEN_IN_PRIVATE_WINDOW: "在隐私窗口中打开",
        CONTEXT_CONTAINER_CLOSED_TAB: "已关闭的标签",
        CONTEXT_CONTAINER_REG_PANELS: "所有常用面板",
        CONTEXT_CONTAINER_WEB_PANELS: "所有网页面板",
        CONTEXT_CONTAINER_REMOVED_PANELS: "已删除的面板",
        CONTEXT_SEPARATE_WIDTH: "独立宽度",
        MENU_PANEL: "MENU_PANEL",
        CONTEXT_MENU_OPEN: "打开于",
        CONTEXT_COPY_ADDRESS: "复制网页面板地址",
        CONTEXT_DESKTOP_VERSION: "显示桌面版网页",
        CONTEXT_MOBILE_VERSION: "显示移动版网页",
        CONTEXT_CONTAINER_TOOLBAR: "工具栏",
        CONTEXT_REMOVE_WEB_PANEL: "删除网页面板",
        CONTEXT_MENU_PANEL: "面板",
        CONTEXT_CONTAINER_BACKWARD_HISTORY: "回退历史",
        CONTEXT_CONTAINER_FORWARD_HISTORY: "前进历史",
        CONTEXT_CONTAINER_CUSTOMIZE_TOOLBAR: "自定义",
        CONTEXT_OPEN_ALL: "打开所有书签",
        CONTEXT_SET_THUMBNAIL: "选择自定义缩略图",
        CONTEXT_CLEAR_THUMBNAIL: "清除自定义缩略图",
        COMMAND_TOGGLE_STARTPAGE_NAVIGATION: "显示起始页导航",
        CONTEXT_ADD_BOOKMARK_TO_SPEEDDIAL: "将书签添加到快速拨号",
        CONTEXT_ADD_FOLDER_TO_SPEEDDIAL: "新建快速拨号文件夹",
        COMMAND_FULLSCREEN: "全屏",
        CONTEXT_REMOVE: "从快速拨号中移除",
        CONTEXT_SEND: "发送",
        COMMAND_MAIL_REPLY: "回复邮件",
        COMMAND_MAIL_REPLY_ALL: "回复全体",
        COMMAND_MAIL_FORWARD: "转发邮件",
        COMMAND_MAIL_MARK_READ: "标记为已读",
        COMMAND_MAIL_MARK_UNREAD: "标记为未读",
        CONTEXT_GOTO: "转到",
        CONTEXT_CONTAINER_MOVE: "移至文件夹",
        CONTEXT_ADD_FLAG: "添加标记",
        CONTEXT_REMOVE_FLAG: "移除标记",
        CONTEXT_CONTAINER_FLAGS: "所有标记",
        CONTEXT_CONTAINER_LABELS: "所有标签",
        CONTEXT_MARK_AS_SPAM: "笔记为垃圾邮件",
        CONTEXT_NOT_SPAM: "非垃圾邮件",
        CONTEXT_CONTAINER_TRASH: "删除元素",
        CONTEXT_SENDER: "发件人",
        CONTEXT_THREAD: "会话",
        CONTEXT_EXPAND_ALL: "展开全部会话",
        CONTEXT_COLLAPSE_ALL: "折叠全部会话",
        CONTEXT_SET_SPEEDDIAL: "用作快速拨号",
        CONTEXT_UNSET_SPEEDDIAL: "从快速拨号中移除",
        CONTEXT_SET_BOOKMARK_BAR: "设为书签栏文件夹",
        CONTEXT_UNSET_BOOKMARK_BAR: "不再设为书签栏文件夹",
        CONTEXT_MOVE_TO_BOOKMARK_BAR: "移动到书签栏文件夹",
        CONTEXT_NEW_ITEM: "新建书签",
        CONTEXT_EMPTY_TRASH: "清空回收站",
        CONTEXT_SETTINGS: "设置",
        CONTEXT_OPEN_ADDRESS: "打开笔记地址",
        CONTEXT_NEW_FROM_SELECTION: "复制所选文本为笔记",
        CONTEXT_OPEN_FILE: "打开",
        CONTEXT_OPEN_IN: "打开图片于",
        CONTEXT_FILEMANAGER: "在资源管理器中显示",
        CONTEXT_COPY_PATH: "复制下载地址",
        CONTEXT_RESTART: "重新下载",
        CONTEXT_STOP: "停止下载",
        CONTEXT_RESUME: "恢复下载",
        CONTEXT_REMOVE_ALL_FINISHED: "删除全部已完成的下载",
        CONTEXT_NEW_STACK: "所选标签组",
        CONTEXT_NEW_STACK_FOR_HOST: "按域名创建标签栈",
        CONTEXT_UNTILE_TABS: "取消平铺",
        CONTEXT_UNMUTE: "取消静音",
        CONTEXT_SAVE: "保存为书签",
        CONTEXT_SAVE_ALL: "保存所有标签为书签",
        CONTEXT_EXPORT: "保存为会话",
        CONTEXT_EXPORT_ALL: "保存所有标签为会话",
        CONTEXT_FILTER_BY: "按网址过滤",
        CONTEXT_COMPOSE_MAIL: "写邮件",
        CONTEXT_VIEW_ALL_MESSAGES: "查看所有邮件",
        CONTEXT_CONTAINER_DEFAULT_ACTION: "默认操作",
        DOCUMENT_OPEN_IN_NEW_TAB: "在新标签页中打开链接",
        DOCUMENT_OPEN_IN_NEW_BACKGROUND_TAB: "在后台新标签页中打开链接",
        DOCUMENT_OPEN_IN_TAB: "打开链接",
        DOCUMENT_OPEN_IN_NEW_WINDOW: "在新窗口中打开链接",
        DOCUMENT_OPEN_IN_PRIVATE_WINDOW: "在隐私窗口中打开链接",
        DOCUMENT_CONTAINER_OPEN_IN_PWA: "在增强型网页应用PWA中打开链接",
        DOCUMENT_CONTAINER_OPEN_IN_PROFILE: "打开链接于另一个配置文件",
        DOCUMENT_CONTAINER_SEND_TO_DEVICES: "发送到您的设备",
        DOCUMENT_ADD_LINK_TO_BOOKMARKS: "链接加入书签",
        DOCUMENT_ADD_LINK_TO_WEBPANEL: "添加链接到网页面板",
        DOCUMENT_SEND_LINK_BY_MAIL: "邮件发送链接",
        DOCUMENT_SAVE_LINK: "链接另存为...",
        DOCUMENT_COPY_LINK_ADDRESS: "复制链接地址",
        DOCUMENT_COPY_LINK_TEXT: "复制链接文本",
        DOCUMENT_CONTAINER_AV: "媒体控件",
        DOCUMENT_CONTAINER_LINK_SELECTION: "选择菜单",
        DOCUMENT_CONTAINER_LINKED_IMAGE: "图片菜单",
        DOCUMENT_CONTAINER_EXTENSIONS: "扩展",
        DOCUMENT_CONTAINER_DEVELOPER_TOOLS: "开发者工具",
        DOCUMENT_BACK: "后退",
        DOCUMENT_FORWARD: "前进",
        DOCUMENT_RELOAD: "刷新",
        COMMAND_ADD_BOOKMARK: "书签页面",
        DOCUMENT_ADD_TO_WEBPANEL: "添加页面到网页面板",
        DOCUMENT_SEND_BY_MAIL: "用邮件发送",
        DOCUMENT_SAVE: "另存为...",
        DOCUMENT_PRINT: "打印...",
        DOCUMENT_CAST: "投影...",
        DOCUMENT_COPY_ADDRESS: "复制页面地址",
        DOCUMENT_QR_CODE: "创建该页面的二维码",
        DOCUMENT_CONTAINER_PLUGIN_ROTATION: "插件轮转命令",
        DOCUMENT_INSPECT: "检查元素",
        COMMAND_TAB_VIEW_PAGE_SOURCE: "查看页面源代码",
        DOCUMENT_OPEN_IMAGE_IN_NEW_TAB: "在新标签页中打开图片",
        DOCUMENT_OPEN_IMAGE_IN_NEW_BACKGROUND_TAB: "在后台标签页中打开图片",
        DOCUMENT_OPEN_IMAGE_IN_TAB: "打开图片",
        DOCUMENT_OPEN_IMAGE_IN_NEW_WINDOW: "在新窗口中打开图片",
        DOCUMENT_OPEN_IMAGE_IN_PRIVATE_WINDOW: "在隐私窗口中打开图片",
        DOCUMENT_CONTAINER_OPEN_IMAGE_IN_PROFILE: "打开链接于另一个配置文件",
        DOCUMENT_SAVE_IMAGE: "图片另存为...",
        DOCUMENT_COPY_IMAGE_ADDRESS: "复制图片地址",
        DOCUMENT_COPY_IMAGE: "复制图片",
        DOCUMENT_SHOW_IMAGE_PROPERTIES: "图片属性",
        DOCUMENT_USE_IMAGE_AS_STARTPAGE_BACKGROUND: "使用图片作为起始页背景",
        DOCUMENT_RELOAD_IMAGE: "重载图片",
        "DOCUMENT_SEARCH_FOR IMAGE": "搜索图片",
        DOCUMENT_SUGGEST_PASSWORD: "推荐密码...",
        DOCUMENT_SHOW_PASSWORDS: "显示所有保存的密码...",
        DOCUMENT_CONTAINER_SPELLCHECK: "拼写检查",
        DOCUMENT_LOOK_UP: "查询“”",
        DOCUMENT_EMOJI: "表情与符号",
        DOCUMENT_UNDO: "撤销",
        DOCUMENT_REDO: "重做",
        DOCUMENT_CUT: "剪切",
        DOCUMENT_COPY: "复制",
        DOCUMENT_PASTE: "粘贴",
        DOCUMENT_PASTE_AS_PLAIN_TEXT: "粘贴为纯文本",
        DOCUMENT_SELECT_ALL: "全选",
        DOCUMENT_GOTO_URL: "前往“”",
        DOCUMENT_ADD_AS_SEARCH_ENGINE: "添加为搜索引擎",
        COMMAND_COPY_SELECTION_TO_NOTE: "复制到笔记",
        DOCUMENT_CONTAINER_NOTES: "所有笔记",
        DOCUMENT_CONTAINER_SPELLCHECK_OPTIONS: "拼写检查选项",
        DOCUMENT_CONTAINER_WRITING_DIRECTION: "书写方向选项",
        DOCUMENT_SEARCH: "在 中搜索“”",
        DOCUMENT_CONTAINER_SEARCH_WITH: "所有搜索引擎",
        DOCUMENT_CONTAINER_SPEECH: "语音命令",
        COMMAND_CLIPBOARD_PASTE_AS_PLAIN_TEXT_OR_PASTE_AND_GO: "粘贴并转到",
        DOCUMENT_CUSTOMIZE: "自定义",
        DOCUMENT_SHOW_FULL_ADDRESS: "显示完整地址",
        DOCUMENT_ADD_TO_CALENDAR: "添加为日历事件",
    }
};
const i18n = VueI18n.createI18n({
    locale: 'en', // set locale
    fallbackLocale: 'en', // set fallback locale
    messages, // set locale messages
    // If you need to specify other options, you can set other options
    // ...
});
app.use(i18n);
app.mount("#menu");
