const Menu = {
    data() {
        return {
            
            fileName: "",
            menus: [{ action: "choise" }],
            filterMenus: [],
            menuSelected: "",
            cmdSelected: "",
            
            currentMenus: {},
            commands: [
                "COMMAND_ADD_BOOKMARK",
                "COMMAND_CLIPBOARD_PASTE_AS_PLAIN_TEXT_OR_PASTE_AND_GO",
                "COMMAND_COPY_SELECTION_TO_NOTE",
                "COMMAND_FULLSCREEN",
                "COMMAND_MAIL_ENABLE_SENDER_VIEW",
                "COMMAND_MAIL_ENABLE_THREADED_VIEW",
                "COMMAND_MAIL_FORWARD",
                "COMMAND_MAIL_GOTO_NEXT_UNREAD",
                "COMMAND_MAIL_GOTO_PREVIOUS_UNREAD",
                "COMMAND_MAIL_MARK_READ",
                "COMMAND_MAIL_MARK_READ_AND_GOTO_NEXT_UNREAD",
                "COMMAND_MAIL_MARK_THREAD_READ",
                "COMMAND_MAIL_MARK_THREAD_UNREAD",
                "COMMAND_MAIL_MARK_UNREAD",
                "COMMAND_MAIL_REPLY",
                "COMMAND_MAIL_REPLY_ALL",
                "COMMAND_TAB_VIEW_PAGE_SOURCE",
                "COMMAND_TOGGLE_STARTPAGE_NAVIGATION",
                "CONTEXT_ADD_BOOKMARK_TO_SPEEDDIAL",
                "CONTEXT_ADD_FLAG",
                "CONTEXT_ADD_FOLDER_TO_SPEEDDIAL",
                "CONTEXT_BOOKMARK",
                "CONTEXT_BOOKMARK_ALL",
                "CONTEXT_BOOKMARK_STACK",
                "CONTEXT_CLEAR_THUMBNAIL",
                "CONTEXT_CLONE",
                "CONTEXT_CLOSE",
                "CONTEXT_CLOSE_LEFT",
                "CONTEXT_CLOSE_OTHER",
                "CONTEXT_CLOSE_RIGHT",
                "CONTEXT_CLOSE_TABSTACK",
                "CONTEXT_COLLAPSE_ALL",
                "CONTEXT_COMPOSE_MAIL",
                "CONTEXT_CONTAINER_BACKWARD_HISTORY",
                "CONTEXT_CONTAINER_CLOSED_TAB",
                "CONTEXT_CONTAINER_CUSTOMIZE_TOOLBAR",
                "CONTEXT_CONTAINER_DEFAULT_ACTION",
                "CONTEXT_CONTAINER_FLAGS",
                "CONTEXT_CONTAINER_FORWARD_HISTORY",
                "CONTEXT_CONTAINER_LABELS",
                "CONTEXT_CONTAINER_MOVE",
                "CONTEXT_CONTAINER_MOVE_TO_WINDOW",
                "CONTEXT_CONTAINER_PERIODIC_TIMER",
                "CONTEXT_CONTAINER_PWA",
                "CONTEXT_CONTAINER_REG_PANELS",
                "CONTEXT_CONTAINER_REMOVED_PANELS",
                "CONTEXT_CONTAINER_SEARCH",
                "CONTEXT_CONTAINER_SORT",
                "CONTEXT_CONTAINER_TOOLBAR",
                "CONTEXT_CONTAINER_TRASH",
                "CONTEXT_CONTAINER_WEB_PANELS",
                "CONTEXT_COPY",
                "CONTEXT_COPY_ADDRESS",
                "CONTEXT_COPY_PATH",
                "CONTEXT_CUSTOMIZE",
                "CONTEXT_CUT",
                "CONTEXT_DELETE",
                "CONTEXT_DESKTOP_VERSION",
                "CONTEXT_EDIT",
                "CONTEXT_EMPTY_TRASH",
                "CONTEXT_EXPAND_ALL",
                "CONTEXT_EXPORT",
                "CONTEXT_EXPORT_ALL",
                "CONTEXT_FILEMANAGER",
                "CONTEXT_FILTER_BY",
                "CONTEXT_GOTO",
                "CONTEXT_HIBERNATE_BACKGROUND",
                "CONTEXT_HIBERNATE_SELECTED_BACKGROUND_TABS",
                "CONTEXT_HIBERNATE_TAB",
                "CONTEXT_HIBERNATE_TABSTACK",
                "CONTEXT_IMPORT",
                "CONTEXT_MARK_AS_SPAM",
                "CONTEXT_MENU_OPEN",
                "CONTEXT_MENU_PANEL",
                "CONTEXT_MOBILE_VERSION",
                "CONTEXT_MOVE",
                "CONTEXT_MOVE_LEFT",
                "CONTEXT_MOVE_RIGHT",
                "CONTEXT_MOVE_STACK_LEFT",
                "CONTEXT_MOVE_STACK_RIGHT",
                "CONTEXT_MOVE_TO_BOOKMARK_BAR",
                "CONTEXT_MUTE",
                "CONTEXT_MUTE_OTHER",
                "CONTEXT_NEW",
                "CONTEXT_NEW_BOOKMARK",
                "CONTEXT_NEW_FOLDER",
                "CONTEXT_NEW_FROM_SELECTION",
                "CONTEXT_NEW_ITEM",
                "CONTEXT_NEW_SEPARATOR",
                "CONTEXT_NEW_STACK",
                "CONTEXT_NEW_STACK_FOR_HOST",
                "CONTEXT_NOT_SPAM",
                "CONTEXT_OPEN_ADDRESS",
                "CONTEXT_OPEN_ALL",
                "CONTEXT_OPEN_FILE",
                "CONTEXT_OPEN_IN",
                "CONTEXT_OPEN_IN_NEW_BACKGROUND_TAB",
                "CONTEXT_OPEN_IN_NEW_TAB",
                "CONTEXT_OPEN_IN_NEW_WINDOW",
                "CONTEXT_OPEN_IN_PRIVATE_WINDOW",
                "CONTEXT_OPEN_IN_TAB",
                "CONTEXT_OPTIMIZE_FS_VIDEOS",
                "CONTEXT_PASTE",
                "CONTEXT_PIN",
                "CONTEXT_RELOAD",
                "CONTEXT_REMOVE",
                "CONTEXT_REMOVE_ALL_FINISHED",
                "CONTEXT_REMOVE_FLAG",
                "CONTEXT_REMOVE_WEB_PANEL",
                "CONTEXT_RENAME",
                "CONTEXT_REOPEN",
                "CONTEXT_RESTART",
                "CONTEXT_RESUME",
                "CONTEXT_SAVE",
                "CONTEXT_SAVE_ALL",
                "CONTEXT_SAVE_SESSION",
                "CONTEXT_SEND",
                "CONTEXT_SENDER",
                "CONTEXT_SENDER_IS_MAILING_LIST",
                "CONTEXT_SEPARATE_WIDTH",
                "CONTEXT_SET_BOOKMARK_BAR",
                "CONTEXT_SET_SPEEDDIAL",
                "CONTEXT_SET_THUMBNAIL",
                "CONTEXT_SETTINGS",
                "CONTEXT_STOP",
                "CONTEXT_TABSTACK_BY_HOST",
                "CONTEXT_TABSTACK_BY_HOSTS",
                "CONTEXT_TABSTACK_BY_SELECTION",
                "CONTEXT_TABSTACK_MOVE",
                "CONTEXT_TABSTACK_REMOVE_FROM",
                "CONTEXT_TABSTACK_RENAME",
                "CONTEXT_TABSTACK_UNGROUP",
                "CONTEXT_THREAD",
                "CONTEXT_TILE_TABS",
                "CONTEXT_TILE_TABSTACK",
                "CONTEXT_TOGGLE_SUBSTRIP_LOCK",
                "CONTEXT_UNMUTE",
                "CONTEXT_UNPIN",
                "CONTEXT_UNSET_BOOKMARK_BAR",
                "CONTEXT_UNSET_SPEEDDIAL",
                "CONTEXT_UNTILE_SELECTION",
                "CONTEXT_UNTILE_TABS",
                "CONTEXT_UNTILE_TABSTACK",
                "CONTEXT_VIEW_ALL_MESSAGES",
                "DOCUMENT_ADD_AS_SEARCH_ENGINE",
                "DOCUMENT_ADD_LINK_TO_BOOKMARKS",
                "DOCUMENT_ADD_LINK_TO_WEBPANEL",
                "DOCUMENT_ADD_TO_CALENDAR",
                "DOCUMENT_ADD_TO_WEBPANEL",
                "DOCUMENT_BACK",
                "DOCUMENT_CAST",
                "DOCUMENT_CONTAINER_AV",
                "DOCUMENT_CONTAINER_DEVELOPER_TOOLS",
                "DOCUMENT_CONTAINER_EXTENSIONS",
                "DOCUMENT_CONTAINER_LINK_SELECTION",
                "DOCUMENT_CONTAINER_LINKED_IMAGE",
                "DOCUMENT_CONTAINER_NOTES",
                "DOCUMENT_CONTAINER_OPEN_IMAGE_IN_PROFILE",
                "DOCUMENT_CONTAINER_OPEN_IN_PROFILE",
                "DOCUMENT_CONTAINER_OPEN_IN_PWA",
                "DOCUMENT_CONTAINER_PLUGIN_ROTATION",
                "DOCUMENT_CONTAINER_SEARCH_WITH",
                "DOCUMENT_CONTAINER_SEND_TO_DEVICES",
                "DOCUMENT_CONTAINER_SPEECH",
                "DOCUMENT_CONTAINER_SPELLCHECK",
                "DOCUMENT_CONTAINER_SPELLCHECK_OPTIONS",
                "DOCUMENT_CONTAINER_WRITING_DIRECTION",
                "DOCUMENT_COPY",
                "DOCUMENT_COPY_ADDRESS",
                "DOCUMENT_COPY_IMAGE",
                "DOCUMENT_COPY_IMAGE_ADDRESS",
                "DOCUMENT_COPY_LINK_ADDRESS",
                "DOCUMENT_COPY_LINK_TEXT",
                "DOCUMENT_CUSTOMIZE",
                "DOCUMENT_CUT",
                "DOCUMENT_EMOJI",
                "DOCUMENT_FORWARD",
                "DOCUMENT_GOTO_URL",
                "DOCUMENT_INSPECT",
                "DOCUMENT_LOOK_UP",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_BACKGROUND_TAB",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_TAB",
                "DOCUMENT_OPEN_IMAGE_IN_NEW_WINDOW",
                "DOCUMENT_OPEN_IMAGE_IN_PRIVATE_WINDOW",
                "DOCUMENT_OPEN_IMAGE_IN_TAB",
                "DOCUMENT_OPEN_IN_NEW_BACKGROUND_TAB",
                "DOCUMENT_OPEN_IN_NEW_TAB",
                "DOCUMENT_OPEN_IN_NEW_WINDOW",
                "DOCUMENT_OPEN_IN_PRIVATE_WINDOW",
                "DOCUMENT_OPEN_IN_TAB",
                "DOCUMENT_PASTE",
                "DOCUMENT_PASTE_AS_PLAIN_TEXT",
                "DOCUMENT_PRINT",
                "DOCUMENT_QR_CODE",
                "DOCUMENT_REDO",
                "DOCUMENT_RELOAD",
                "DOCUMENT_RELOAD_IMAGE",
                "DOCUMENT_SAVE",
                "DOCUMENT_SAVE_IMAGE",
                "DOCUMENT_SAVE_LINK",
                "DOCUMENT_SEARCH",
                "DOCUMENT_SEARCH_FOR IMAGE",
                "DOCUMENT_SELECT_ALL",
                "DOCUMENT_SEND_BY_MAIL",
                "DOCUMENT_SEND_LINK_BY_MAIL",
                "DOCUMENT_SHOW_FULL_ADDRESS",
                "DOCUMENT_SHOW_IMAGE_PROPERTIES",
                "DOCUMENT_SHOW_PASSWORDS",
                "DOCUMENT_SUGGEST_PASSWORD",
                "DOCUMENT_UNDO",
                "DOCUMENT_USE_IMAGE_AS_STARTPAGE_BACKGROUND",
                "MENU_PANEL",

            ]
        };
    },
    methods: {
        loadJson(e) {
            this.readJson(e.target.files[0]);
        },
        readJson(file) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let json = JSON.parse(e.target.result);
                json.pop();
                this.loadMenu(json);
                json.forEach(menu=>{
                    console.log(menu.action)
                })
            };
            reader.readAsText(file);
        },
        loadMenu(json) {
            this.menus = json;
        },
        showMenu() {
            let cmd = this.menuSelected;
            this.currentMenus = {cmd:cmd,menu:this.menus[cmd].children};
        },
        searchMenu() {
            this. filterMenus = [];
            this.currentMenus = {};
            let cmd = this.cmdSelected;
            console.log(cmd);
            this.menus.forEach((menu, index) => {
                if ("children" in menu) {
                    menu.children.forEach((m, i) => {
                        if (m.action == cmd) {
                            this. filterMenus.push({ rootIndex: index, action: this.menus[index].action, cmd: cmd });
                        } else if ("children" in m) {
                            m.children.forEach(n => {
                                if (n.action == cmd) {
                                    this. filterMenus.push({ rootIndex: index, action: [this.menus[index].action,m.action],cmd: cmd });
                                }
                            });
                        }
                    });
                }
            });
        },
        gMenu(item) {
            this.currentMenus = { action: item.action, menu: this.menus[item.rootIndex].children,cmd:item.cmd };
        }
    },
    created() {
        this.menuSelected = this.menus[0].action;
        this.cmdSelected = this.commands[0];

    }
};
const messages = {
    en: {
        choise: 'Select a menu',
        tab: 'Select a menu'
    },
    zh: {
        choise: '选择一个菜单',
        vivaldi: "Vivaldi 按钮菜单",
        menubar: "水平式",
        image: "图片",
        docedit: "网页文本域",
        selection: "选择",
        link: "链接",
        audiovideo: "音视频",
        page: "页面",
        mailsearchlist: "消息列表",
        contactlist: "联系人",
        startpage: "开始页",
        speeddialitem: "快速拨号按钮",
        startpagebar: "起始页栏",
        panelbar: "面板栏",
        panelbaritem: "面板栏按钮",
        tab: "标签",
        closedtab: "标签回收站",
        tabbar: "标签栏",
        tabstackthumbnails: "标签组缩略图",
        windowlist: "窗口列表",
        bookmarklist: "书签列表",
        bookmarkbar: "书签栏",
        bookmarkbaritem: "书签栏按钮",
        backwardbutton: "后退按钮",
        forwardbutton: "前进按钮",
        rewindbutton: "快退按钮",
        fastforwardbutton: "快进按钮",
        reloadbutton: "重载按钮",
        homebutton: "主页按钮",
        urledit: "地址栏文本域",
        downloadlist: "下载列表",
        historylist: "历史列表",
        uiedit: "文本域",
        noteslist: "笔记列表",
        CONTEXT_NEW :"新建标签",
        CONTEXT_RELOAD: "刷新标签",
        CONTEXT_CLONE :"复制标签",
        CONTEXT_PIN :"锁定标签",
        CONTEXT_UNPIN: "取消锁定",
        CONTEXT_MOVE :"移动标签",
        CONTEXT_MOVE_LEFT:"左侧",
        CONTEXT_MOVE_RIGHT :"右侧",
        CONTEXT_CONTAINER_MOVE_TO_WINDOW:"至窗口",
        CONTEXT_CONTAINER_PERIODIC_TIMER:"定时刷新",
        CONTEXT_MUTE:"静音标签",
        CONTEXT_MUTE_OTHER:"静音其他标签",
        CONTEXT_OPTIMIZE_FS_VIDEOS:"优化全屏视频",
        CONTEXT_BOOKMARK:"加入书签",
        CONTEXT_BOOKMARK_STACK:"标签组加入书签",
        CONTEXT_BOOKMARK_ALL:"全部加入书签",
        CONTEXT_SAVE_SESSION:"保存全部标签为会话",
        CONTEXT_TABSTACK_BY_SELECTION:"所选标签建组",
        CONTEXT_TABSTACK_BY_HOST:"按域名创建标签栈",
        CONTEXT_TABSTACK_BY_HOSTS:"按域名创建标签栈",
        CONTEXT_TABSTACK_RENAME:"重命名标签组",
        CONTEXT_TABSTACK_MOVE:"移动标签组",
        CONTEXT_TABSTACK_REMOVE_FROM:"从标签组移除",
        CONTEXT_TABSTACK_UNGROUP:"解散标签组",
        CONTEXT_TILE_TABSTACK:"平铺标签组",
        CONTEXT_UNTILE_TABSTACK:"取消平铺标签组",
        CONTEXT_TILE_TABS:"平铺标签",
        CONTEXT_UNTILE_SELECTION:"取消平铺所选标签",
        CONTEXT_HIBERNATE_TAB:"休眠标签",
        CONTEXT_HIBERNATE_SELECTED_BACKGROUND_TABS:"休眠所选后台标签",
        CONTEXT_HIBERNATE_TABSTACK:"休眠标签组",
        CONTEXT_HIBERNATE_BACKGROUND:"休眠后台标签",
        CONTEXT_CLOSE:"关闭标签",
        CONTEXT_CLOSE_TABSTACK:"关闭标签组",
        CONTEXT_CLOSE_OTHER:"关闭其他标签",
        CONTEXT_CLOSE_LEFT:"关闭左侧标签",
        CONTEXT_CLOSE_RIGHT:"关闭右侧标签",
        CONTEXT_REOPEN:"重新打开关闭的标签",
        CONTEXT_CONTAINER_PWA:"所有增强型网页应用 PWA",
        CONTEXT_CUSTOMIZE:"自定义",
        CONTEXT_TOGGLE_SUBSTRIP_LOCK:"锁定第二行标签",
        CONTEXT_NEW_BOOKMARK:"新建书签",
        CONTEXT_NEW_FOLDER:"新建文件夹",
        CONTEXT_NEW_SEPARATOR:"新增分割线",
        CONTEXT_CONTAINER_SORT:"排序选项",
        CONTEXT_EDIT:"编辑",
        CONTEXT_RENAME:"重命名",
        CONTEXT_CUT:"剪切",
        CONTEXT_COPY:"复制" ,
        CONTEXT_PASTE:"粘贴",
        CONTEXT_DELETE:"删除",
        CONTEXT_OPEN_IN_NEW_TAB:"在新标签页打开",
        CONTEXT_OPEN_IN_NEW_BACKGROUND_TAB:"在后台标签页打开",
        CONTEXT_OPEN_IN_TAB:"打开",
        CONTEXT_OPEN_IN_NEW_WINDOW:"在新窗口中打开",
        CONTEXT_OPEN_IN_PRIVATE_WINDOW:"在隐私窗口中打开",
        CONTEXT_CONTAINER_CLOSED_TAB:"已关闭的标签",
        CONTEXT_CONTAINER_REG_PANELS:"所有常用面板",
        CONTEXT_CONTAINER_WEB_PANELS:"所有网页面板",
        CONTEXT_CONTAINER_REMOVED_PANELS:"已删除的面板",
        CONTEXT_SEPARATE_WIDTH:"独立宽度",
        MENU_PANEL:"MENU_PANEL",
        CONTEXT_MENU_OPEN:"打开于",
        CONTEXT_COPY_ADDRESS:"复制网页面板地址",
        CONTEXT_DESKTOP_VERSION:"显示桌面版网页",
        CONTEXT_MOBILE_VERSION:"显示移动版网页",
        CONTEXT_CONTAINER_TOOLBAR:"工具栏",
        CONTEXT_REMOVE_WEB_PANEL:"删除网页面板",
        CONTEXT_MENU_PANEL:"面板",
        CONTEXT_CONTAINER_BACKWARD_HISTORY:"回退历史",
        CONTEXT_CONTAINER_FORWARD_HISTORY:"前进历史",
        CONTEXT_CONTAINER_CUSTOMIZE_TOOLBAR:"自定义",
        CONTEXT_OPEN_ALL:"打开所有书签",
        CONTEXT_SET_THUMBNAIL:"选择自定义缩略图",
        CONTEXT_CLEAR_THUMBNAIL:"清除自定义缩略图",
        COMMAND_TOGGLE_STARTPAGE_NAVIGATION:"显示起始页导航",
        CONTEXT_ADD_BOOKMARK_TO_SPEEDDIAL:"将书签添加到快速拨号",
        CONTEXT_ADD_FOLDER_TO_SPEEDDIAL:"新建快速拨号文件夹",
        COMMAND_FULLSCREEN:"全屏",
        CONTEXT_REMOVE:"从快速拨号中移除",
        CONTEXT_SEND:"发送",
COMMAND_MAIL_REPLY:"回复邮件",
COMMAND_MAIL_REPLY_ALL:"回复全体",
COMMAND_MAIL_FORWARD:"转发邮件",
COMMAND_MAIL_MARK_READ:"标记为已读",
COMMAND_MAIL_MARK_UNREAD:"标记为未读",
CONTEXT_GOTO:"转到",
CONTEXT_CONTAINER_MOVE:"移至文件夹",
CONTEXT_ADD_FLAG:"添加标记",
CONTEXT_REMOVE_FLAG:"移除标记",
CONTEXT_CONTAINER_FLAGS:"所有标记",
CONTEXT_CONTAINER_LABELS:"所有标签",
CONTEXT_MARK_AS_SPAM:"笔记为垃圾邮件",
CONTEXT_NOT_SPAM:"非垃圾邮件",
CONTEXT_CONTAINER_TRASH:"删除元素",
CONTEXT_SENDER:"发件人",
CONTEXT_THREAD:"会话",
CONTEXT_EXPAND_ALL:"展开全部会话",
CONTEXT_COLLAPSE_ALL:"折叠全部会话",
CONTEXT_SET_SPEEDDIAL:"用作快速拨号",
CONTEXT_UNSET_SPEEDDIAL:"从快速拨号中移除",
CONTEXT_SET_BOOKMARK_BAR:"设为书签栏文件夹",
CONTEXT_UNSET_BOOKMARK_BAR:"不再设为书签栏文件夹",
CONTEXT_MOVE_TO_BOOKMARK_BAR:"移动到书签栏文件夹",
CONTEXT_NEW_ITEM:"新建书签",
CONTEXT_EMPTY_TRASH:"清空回收站",
CONTEXT_SETTINGS:"设置",
CONTEXT_OPEN_ADDRESS:"打开笔记地址",
CONTEXT_NEW_FROM_SELECTION:"复制所选文本为笔记",
CONTEXT_OPEN_FILE:"打开",
CONTEXT_OPEN_IN:"打开图片于",
CONTEXT_FILEMANAGER:"在资源管理器中显示",
CONTEXT_COPY_PATH:"复制下载地址",
CONTEXT_RESTART:"重新下载",
CONTEXT_STOP:"停止下载",
CONTEXT_RESUME:"恢复下载",
CONTEXT_REMOVE_ALL_FINISHED:"删除全部已完成的下载",
CONTEXT_NEW_STACK:"所选标签组",
CONTEXT_NEW_STACK_FOR_HOST:"按域名创建标签栈",
CONTEXT_UNTILE_TABS:"取消平铺",
CONTEXT_UNMUTE:"取消静音",
CONTEXT_SAVE:"保存为书签",
CONTEXT_SAVE_ALL:"保存所有标签为书签", 
CONTEXT_EXPORT:"保存为会话",
CONTEXT_EXPORT_ALL:"保存所有标签为会话",
CONTEXT_FILTER_BY:"按网址过滤",
CONTEXT_COMPOSE_MAIL:"写邮件",
CONTEXT_VIEW_ALL_MESSAGES:"查看所有邮件",
CONTEXT_CONTAINER_DEFAULT_ACTION:"默认操作",
DOCUMENT_OPEN_IN_NEW_TAB:"在新标签页中打开链接",
DOCUMENT_OPEN_IN_NEW_BACKGROUND_TAB:"在后台新标签页中打开链接",
DOCUMENT_OPEN_IN_TAB:"打开链接",
DOCUMENT_OPEN_IN_NEW_WINDOW:"在新窗口中打开链接",
DOCUMENT_OPEN_IN_PRIVATE_WINDOW:"在隐私窗口中打开链接",
DOCUMENT_CONTAINER_OPEN_IN_PWA:"在增强型网页应用PWA中打开链接",
DOCUMENT_CONTAINER_OPEN_IN_PROFILE:"打开链接于另一个配置文件",
DOCUMENT_CONTAINER_SEND_TO_DEVICES:"发送到您的设备",
DOCUMENT_ADD_LINK_TO_BOOKMARKS:"链接加入书签",
DOCUMENT_ADD_LINK_TO_WEBPANEL:"添加链接到网页面板",
DOCUMENT_SEND_LINK_BY_MAIL:"邮件发送链接",
DOCUMENT_SAVE_LINK:"链接另存为...",
DOCUMENT_COPY_LINK_ADDRESS:"复制链接地址",
DOCUMENT_COPY_LINK_TEXT:"复制链接文本",
DOCUMENT_CONTAINER_AV:"媒体控件",
DOCUMENT_CONTAINER_LINK_SELECTION:"选择菜单",
DOCUMENT_CONTAINER_LINKED_IMAGE:"图片菜单",
DOCUMENT_CONTAINER_EXTENSIONS:"扩展",
DOCUMENT_CONTAINER_DEVELOPER_TOOLS:"开发者工具",
DOCUMENT_BACK:"后退",
DOCUMENT_FORWARD:"前进",
DOCUMENT_RELOAD:"刷新",
COMMAND_ADD_BOOKMARK:"书签页面",
DOCUMENT_ADD_TO_WEBPANEL:"添加页面到网页面板",
DOCUMENT_SEND_BY_MAIL:"用邮件发送",
DOCUMENT_SAVE:"另存为...",
DOCUMENT_PRINT:"打印...",
DOCUMENT_CAST:"投影...",
DOCUMENT_COPY_ADDRESS:"复制页面地址",
DOCUMENT_QR_CODE:"创建该页面的二维码",
DOCUMENT_CONTAINER_PLUGIN_ROTATION:"插件轮转命令",
DOCUMENT_INSPECT:"检查元素",
COMMAND_TAB_VIEW_PAGE_SOURCE:"查看页面源代码",
DOCUMENT_OPEN_IMAGE_IN_NEW_TAB:"在新标签页中打开图片",
DOCUMENT_OPEN_IMAGE_IN_NEW_BACKGROUND_TAB:"在后台标签页中打开图片",
DOCUMENT_OPEN_IMAGE_IN_TAB:"打开图片",
DOCUMENT_OPEN_IMAGE_IN_NEW_WINDOW:"在新窗口中打开图片",
DOCUMENT_OPEN_IMAGE_IN_PRIVATE_WINDOW:"在隐私窗口中打开图片",
DOCUMENT_CONTAINER_OPEN_IMAGE_IN_PROFILE:"打开链接于另一个配置文件",
DOCUMENT_SAVE_IMAGE:"图片另存为...",
DOCUMENT_COPY_IMAGE_ADDRESS:"复制图片地址",
DOCUMENT_COPY_IMAGE:"复制图片",
DOCUMENT_SHOW_IMAGE_PROPERTIES:"图片属性",
DOCUMENT_USE_IMAGE_AS_STARTPAGE_BACKGROUND:"使用图片作为起始页背景",
DOCUMENT_RELOAD_IMAGE:"重载图片",
"DOCUMENT_SEARCH_FOR IMAGE":"搜索图片",
DOCUMENT_SUGGEST_PASSWORD:"推荐密码...",
DOCUMENT_SHOW_PASSWORDS:"显示所有保存的密码...",
DOCUMENT_CONTAINER_SPELLCHECK:"拼写检查",
DOCUMENT_LOOK_UP:"查询“”",
DOCUMENT_EMOJI:"表情与符号",
DOCUMENT_UNDO:"撤销",
DOCUMENT_REDO:"重做",
DOCUMENT_CUT:"剪切",
DOCUMENT_COPY:"复制",
DOCUMENT_PASTE:"粘贴",
DOCUMENT_PASTE_AS_PLAIN_TEXT:"粘贴为纯文本",
DOCUMENT_SELECT_ALL:"全选",
DOCUMENT_GOTO_URL:"前往“”",
DOCUMENT_ADD_AS_SEARCH_ENGINE:"添加为搜索引擎",
COMMAND_COPY_SELECTION_TO_NOTE:"复制到笔记",
DOCUMENT_CONTAINER_NOTES:"所有笔记",
DOCUMENT_CONTAINER_SPELLCHECK_OPTIONS:"拼写检查选项",
DOCUMENT_CONTAINER_WRITING_DIRECTION:"书写方向选项",
DOCUMENT_SEARCH:"在 中搜索“”",
DOCUMENT_CONTAINER_SEARCH_WITH:"所有搜索引擎",
DOCUMENT_CONTAINER_SPEECH:"语音命令",
COMMAND_CLIPBOARD_PASTE_AS_PLAIN_TEXT_OR_PASTE_AND_GO:"粘贴并转到",
DOCUMENT_CUSTOMIZE:"自定义",
DOCUMENT_SHOW_FULL_ADDRESS:"显示完整地址",
DOCUMENT_ADD_TO_CALENDAR:"添加为日历事件"



    }
}
const i18n = VueI18n.createI18n({
    locale: 'zh', // set locale
    fallbackLocale: 'en', // set fallback locale
    messages, // set locale messages
    // If you need to specify other options, you can set other options
    // ...
});
Vue.createApp(Menu).use(i18n).mount("#menu");
